### ISSUE TITLE
Refunds - Unable to refund orders placed via Box Office

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#116]
**Steps to Reproduce:**

1. Open Box Office 
2. Add tickets to cart & create a cash order
3. Add tickets to cart & create a credit card order
4. Open the event Dashboard
5. Navigate to _Manage Orders_ from Tools
6. Locate the first order, and refund
7. Locate the second order, and refund

**Expected Behavior:**

Upon clicking _refund_, I expect to see:

- A refund success message 

- Inventory returned to the original pre-purchase state

- Customer is credited via the payment processor. Credit is reflected accordingly in Big Neon reporting.

- Customer receives an automated email confirmation detailing the credit, the refund process, and explains the invalidation of tickets

**Observed Behavior:**

Upon clicking _refund_, I see:

- An error message stating that a refund cannot be completed because tickets have been transferred. Multiple box office order attempts across several events yielded this result. No tickets were transferred. Error occurs with both Cash and Credit method of payment.

-Screengrab here: https://cl.ly/70ae398f805f

**Comment by Jasonvdb** [comment]
I think the message is caused because the tickets go to the box office user's wallet first before being transferred. @mikethetike ?

But I think even if that error is managed you still shouldn't be able to do a refund because box office doesn't use stripe for payments, the box office payments happen outside the system so the customer cannot be credited via the payment processor. The inventory being returned could still happen though.

@zmelamed what do you think?

**Comment by Krakaw** [comment]
Currently from a tech point of view, you're 100% right @jay. The ticket is transferred to the new owner, so it cannot be refunded using the current system.
@harrisonlemon how would the box office usually issue a refund from the box office?

**Comment by zmelamed** [comment]
Issuing a refund via the box office should at a minimum reverse the purchase in the records as an accounting/reporting consideration. 

If I collect $20 in cash from someone attending the event to buy a ticket at the box office, and then something happens, like the box office operator sold a ticket to the wrong event, or the purchaser was underage for a 21+ show and denied entry the venue may give the person back their $20 from their system, so will need to make sure the system also tracks this refund and reported sales balance.

If there is an associated email where a order confirmation was sent, that same email should receive a refund confirmation email. 

Might we need a `refundable` status that can be set to true for some transferred tickets (like those transferred via the box office operation)? A normal box office wouldn't have this concept of it being locked because it's a transferred ticket.

**Comment by harrisonlemon** [comment]
@zmelamed You nailed it: even though we, as the ticketing company, will not be physically holding funds for box office transactions, refunds should still be reflected within all inventory components & on reporting. 

Additionally agree that if there is an associated email where an order confirmation was sent, that same email should receive a refund confirmation email. Box office user should have the option to add an email address to the order post-refund to accommodate 'receipt' requests. This is a common on-site request: a quick-sale onsite took place, and no customer data was captured. The order was then refunded. The customer asks for an email confirmation to verify the refund before leaving the box office.
