### ISSUE TITLE
Roles - Admin permission does not allow user to add or edit artists in artist database

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#168]
**Steps to Reproduce:**

1. Navigate to Organization Settings
2. Select 'Team'
3. Add a user with 'Admin' role
4. Accept the invite & login to Big Neon
5. Choose 'Artists' from the left-hand column
6. Create a new artist & attempt to save
7. Next, select an existing artist from the artist database and update the artist information. Attempt to save.

**Expected Behavior:**

As an org ADMIN, I expect that I'd be able to add new artists to my org's artist database as needed. 

I also expect that I would be able to update artist's profiles as needed. This includes: artist name, biography, social media links, video files, etc. 

**Observed Behavior:**

Users with ADMIN level permissions receive an error when attempting to create new artists in their org's artist database. User receives the same error when attempting to update information within a pre-existing artist from the artist database.

Error message: User does not have required permissions

Screengrab: https://cl.ly/3c8245d061c7

**Comment by Timo614** [comment]
I see the issue here and it's related to two things:

- We don't allow public artists to be modified by organization members (once an artist is public only full admins (not org but cross system) can edit it as other organizations may be using it)
- The bn-web is not passing an organization to the create artists endpoint so it's attempting to make public artists (only full admins can make public artists; organizations can create private artists for their use only which may be made public by a full admin later)

So it sounds like we need to: 
- Include the organization_id when creating new artists on the bn-web side
- Determine the ideal edit flow here for organization members

What behavior do we want if someone wishes to edit a public artist?

One option:
- On edit of public artists make a new artist that's organization specific and a child of the existing artist
- Any field that's null is then inherited from its parent
- Only one organization version of an artist is allowed
- The artists listing for an organization with an child artist does not list the parent artist only the child
- All existing events for that artist are updated to point to the new artist id

Does that make sense? Alternatively we could disable the editing for any public artist. If these artists were created correctly (with the organization_id) they'd be private so the user would have access to edit them so long as we didn't make it public.

With the alternative:
- bn-web change to pass organization_id when creating artists
- removal of edit button for public artists outside of full admins
- any existing artists in production should likely be made private and organization owned unless we intended them to be public / read only

**Comment by harrisonlemon** [comment]
The first option seems like the best route, especially for our client's needs - what are your thoughts @zmelamed?

**Comment by Timo614** [comment]
Since this is client reported for now I'll go ahead and move forward with the latter approach of making these private. I'll make a new issue about the other flow which we can iterate on as we have more clients / have situations where the artists may be used by multiple events.

@zmelamed just a heads up with the existing solution all system admin created artists will be public so they will not be editable by an organization. I'll make sure we remove that button in those cases for the time being but we may want to support the other flow I mentioned above in the future so they can edit them. 

For this issue I'll do the following:
- Add a migration which adjusts the existing artists to belong to a given organization and be private if they only are associated with one organization's events.
- Adjust bn-web to pass in organization_id if the user is creating an artist while associated with a given organization.
- Adjust bn-web to remove the edit button (temporarily pending the other flow) for any public artist when the user is not an admin

**Comment by zmelamed** [comment]
Thanks, the first option you mention is the correct behavior. We're going to do a deep dive on this in the near future.

**Comment by Timo614** [comment]
Should I hold off on adjusting the production artists to be private (was thinking we'd want to adjust the ones in play now so that organizations could edit them as they see fit)?

Have two PRs set:

API side: https://github.com/big-neon/bn-api/compare/master...Timo614:artists-adjust-for-private-access?expand=1 migration to adjust all applicable artists to belong to the organizations they have events setup for (to allow any of them to be edited but we could hold off on this aspect if we want to wait for the other option)

Web side: hhttps://github.com/big-neon/bn-web/pull/1476 locks down editing of public artists to just admins, fixes the create flow for organization members (will be useful with https://github.com/big-neon/bigneon/issues/171 as well since we need the organization_id on the API side to make an organization specific artist child if we go that direction flow wise)

**Comment by nine-tari** [comment]
This was merged into master for the bn-web side. We have a separate issue for changing the artist flow to allow for organization versions of public artists (if we decide to go that route).

Let me know if we should update the existing public artists in production to be owned by their organizations via that migration (have a branch mentioned above which has a migration for that) or if we only want to do this going forward (the bn-web side). Right now all of the old artists will not be editable as they are all set as public from the earlier flow.

Otherwise will put this in the review pile for the bn-web side since it should be set going forward.

**Comment by Timo614** [comment]
Was thinking since bn-web will always create private artists as we're now passing in the organization_id it probably makes sense from a client perspective to update the existing records as mentioned above. Ended up pushing up the PR I made https://github.com/big-neon/bn-api/pull/1299 to handle that aspect. The bn-web side has already been merged so this just makes it so previously created ones are in the same format (private and org owned).

**Comment by nine-tari** [comment]
This should be set now - the API side (a migration to make private those that can) and the web side to pass it in so future ones are private is in place. We have another issue for changing up the flow in the future but this should be set for the qa flow now I think.

**Comment by Anziskavds** [comment]
Reviewed and it is working as expected. Admin can create and update artists.

**Comment by Anziskavds** [comment]
Tested on Prod and it's working as expected.
