### ISSUE TITLE
Fan Profile/Management - Fan Profile Redesign

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#177]
An org member should be able to view a fans profile which includes the following:
- Users Name
- Users Email
- Users Location (if available)
- Event Activity
  - Organized by Events filtered by Upcoming and Past (Default: Upcoming)
  - Each Event Summary Card should contain the following:
    - Event Name
    - Event Name
    - Event Venue
      - Name, City, State
    - Event Date and Time

* Each activity item should start collapsed below the the Event Summary Card
  * Activity Items (The activity feed pattern and objects will be used throughout studio including #176 ):
    * Purchase
      * [Purchasing User Name] purchased [# tickets] to [Event Name] 
      * If tickets to multiple events are purchased in the same order each should have it's own purchase item like "Sam Johnson purchased 3 Tickets to Ariana Grande..."
      * Expanded View
        * Event Venue 
        * Name, City, State
        * Event Date and Time
        * Code Used in order  (Code, Type, Discount Amount if any)
        * Total Tickets included in Order for Event
        * Order Total for related event
        * (Refunded amount if any)
        * CTA: `View Order` which links to Order Management View
    * Attendee Checked-in
      * [User Name] checked-in to [Event Name] ([# Tickets])
      * ~~Only one activity card per attendee (if they check in multiple tickets to the event there should only be one check in activity and the timestamp should be for the first check-in)~~
      * UPDATED: Issue created to group checkins into one activity card at: big-neon/bn-web#1656
      * Expanded View should show:
        * Checked-in Tickets
        * Ticket ID (Order #) by [Door Person Name] on [Timestamp]
    * Refund Created
      * [Refunder Name] refunded [refund amount] to [User Name]
      * Expanded View should show:
        * Items Refunded
          * Item Name
          * Item ID
          * Item Value
        * Reason for refund
    * Ticket Transfer (3 states)
      * Each state includes:
        * Tickets
          * Ticket ID (Order # Link To Order)
        * Initiated By
          * Transferrer Name
          * Date/Time
        * Transfer Address
          * Email/Phone number transfer was sent to
      * Successful State:
        * Accepted By
          * User Name
          * Date/Time
      * Pending
        * If admin or higher:
          * CTA: `Cancel Transfer`
            * When Clicked the they should confirm the cancel transfer action
      * Cancelled
        * Cancelled By
          * User Name
          * Date/Time

Activity Types Card Designs: https://share.goabstract.com/2d291b35-4b13-439a-b93e-33ab76bac474?mode=design&sha=0a28701774cc425cd73fc2b4c0c91bec9ee45264

Profile Prototype: https://sketch.cloud/s/ebkxW/a/vqp8d4/play

Abstract: https://share.goabstract.com/7e97341b-54bb-46cc-a5c8-541e74601a5c?mode=design&sha=0a28701774cc425cd73fc2b4c0c91bec9ee45264

![image.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/d9527b58-81a7-4025-8ea4-ab1b9524fe5a)
![image.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/0e87cb89-4bb8-4312-a247-f719b9b26baa)

**Comment by Jasonvdb** [comment]
@zmelamed @Tas4tari there's no mobile designs for these that I've seen, should we wait for them or should @shanimal08 and I just try make it work for mobile and we update later?

**Comment by Tas4tari** [comment]
@zmelamed I see that the mobile designs have been uploaded on Asana, please let us know if they have been approved and if we can utilise them for the Mobile aspect of things.

**Comment by zmelamed** [comment]
Yes those are approved. They should be in abstract as well

**Comment by Tas4tari** [comment]
@Jasonvdb https://share.goabstract.com/789976a4-e00a-4eb1-a372-b9ae22bad966

**Comment by Jasonvdb** [comment]
Are there any other designs for mobile though? Those are just the card designs for specific activity types.

Can't find mobile versions of what the whole view should look like for the pages in this collection: https://share.goabstract.com/eb756c85-a087-4208-b3d3-ac4d5ca002a9

**Comment by Tas4tari** [comment]
https://app.goabstract.com/projects/20f4bd60-ab00-11e8-b694-6fcb86ba37e4/branches/b0d7295f-fc30-4611-9d14-311433a02d3f/collections/5534e43a-92da-471c-aea4-38b976691e88

**Comment by Tas4tari** [comment]
@Jasonvdb Here is the link:https://app.goabstract.com/projects/20f4bd60-ab00-11e8-b694-6fcb86ba37e4/branches/7c283543-de8a-4c6c-9e08-6b3c2003509b/commits/a54fa028215c90ed48ac6de2121f27a64f55a276/files/544D16EE-9C75-4DA0-83BA-D2C1A532A823/layers/BCAD9541-51F9-484D-8D3F-4BC21CF89ED7?nonce=3716fa58-f3ae-4b2a-8461-29a28d9806ff

**Comment by Anziskavds** [comment]
Testing in progress

**Comment by Anziskavds** [comment]
Tested on Develop and not all of the fields as per requirements does reflect as expected.

Steps to reproduce:

- Event activity: Organized by Events filtered by Upcoming and Past (Default: Upcoming), **this doesn't show** https://cl.ly/3aeda3a0219e
- Event Summary Card: Event name is written twice on the requirements, not sure if it should show somewhere else and where it should show the second time.
- Instead of [Purchasing User Name] purchased [# tickets] to [Event Name] it shows as follow **Purchased [# tickets] to [Event Name] (Order #)** https://cl.ly/6c4fa07c64a3
-  Purchase Expanded View: Code Used in order (Code, **Type**, Discount Amount if any) everything appears except for the **Type** https://cl.ly/8f52a7a63da2
- Purchase: (Refunded amount if any), the refund amount does not reflect under the purchase expanded view https://cl.ly/01d1bcfb8736  https://cl.ly/e968594047b7
- There was two tickets refunded and it doesn't show the quantity of tickets which was refunded only the total of the two tickets? Please advise if it should show the quantity of tickets refunded https://cl.ly/e968594047b7
- Attendee Checked-in: [User Name] checked-in to [Event Name] **([# Tickets])**, the # tickets shows **(undefined)** https://cl.ly/311c74159f6e
- Attendee Checked-in expanded view: Ticket ID (Order #) **by** [Door Person Name] on [Timestamp], instead of **by** it shows **scanned by**? https://cl.ly/90f9101c3590
- Refund Created: [Refunder Name] refunded [refund amount] to **[User Name]** (Order #), the User Name doesn't show. https://cl.ly/37e6232bb561
- Refund created expanded view should show:
Items Refunded
Item Name 
**(Undefined?)** (Not sure why this shows)
Item ID
Item Value
Reason for refund
https://cl.ly/0da4e39141db
- Ticket transfer (3 states) each state incl: 
Tickets
Ticket ID (Order # Link To Order)
Initiated By
Transferrer Name
**Date/Time? - Doesn't show** 
Transfer Address
Email/Phone number transfer was sent to
https://cl.ly/b67072fb934b
- Ticket transfer Successful State:
Accepted By
User Name
**Date/Time? - Doesn't show**
- Ticket transfer Cancelled state:
**Cancelled By**
**User Name**
**Date/Time**
None of the above shows
https://cl.ly/b2895765358e

**Comment by shanimal08** [comment]
Hi @Anziskavds, thanks so much :D I just added comments to each part on your list, will make a pr for the fixes now

Event activity: Organized by Events filtered by Upcoming and Past (Default: Upcoming), this doesn't show https://cl.ly/3aeda3a0219e

- added in

Event Summary Card: Event name is written twice on the requirements, not sure if it should show somewhere else and where it should show the second time.

- was listed twice by accident

Instead of [Purchasing User Name] purchased [# tickets] to [Event Name] it shows as follow Purchased [# tickets] to [Event Name] (Order #) https://cl.ly/6c4fa07c64a3

- added name

Purchase Expanded View: Code Used in order (Code, Type, Discount Amount if any) everything appears except for the Type https://cl.ly/8f52a7a63da2
- Type is there, list was confusing

Purchase: (Refunded amount if any), the refund amount does not reflect under the purchase expanded view https://cl.ly/01d1bcfb8736 https://cl.ly/e968594047b7
- Not in designs, if still wanted can we get a design? not sure where to put it

There was two tickets refunded and it doesn't show the quantity of tickets which was refunded only the total of the two tickets? Please advise if it should show the quantity of tickets refunded https://cl.ly/e968594047b7

- check per ticket fee - sorted

Attendee Checked-in: [User Name] checked-in to [Event Name] ([# Tickets]), the # tickets shows (undefined) https://cl.ly/311c74159f6e
- Resolved but check ins will be grouped (another issue)

Attendee Checked-in expanded view: Ticket ID (Order #) by [Door Person Name] on [Timestamp], instead of by it shows scanned by? https://cl.ly/90f9101c3590
- we agreed to change the wording to make more sense

Refund Created: [Refunder Name] refunded [refund amount] to [User Name] (Order #), the User Name doesn't show. https://cl.ly/37e6232bb561
- added name

Refund created expanded view should show:
Items Refunded
Item Name
(Undefined?) (Not sure why this shows) -  took it out, will create an issue, need ticket type from api

Item ID
Item Value
Reason for refund
https://cl.ly/0da4e39141db


Ticket transfer (3 states) each state incl:
Tickets
Ticket ID (Order # Link To Order)
Initiated By
Transferrer Name
Date/Time? - Doesn't show - Done
Transfer Address
Email/Phone number transfer was sent to
https://cl.ly/b67072fb934b

Ticket transfer Successful State:
Accepted By
User Name
Date/Time? - Doesn't show 
Ticket transfer Cancelled state:
Cancelled By 
User Name
Date/Time
None of the above shows
https://cl.ly/b2895765358e

Done

**Comment by Anziskavds** [comment]
- Tested on Develop.

- Only one activity card per attendee (if they check in multiple tickets to the event there should only be one check in activity and the timestamp should be for the first check-in). There is 4  activity cards for the same attendee who checked in 4 tickets.
https://cl.ly/cfcaea014a45


- Ticket transfer Successful State:
 
**Accepted By**
User Name
**Date/Time? - Doesn't show**
Ticket transfer Cancelled state:

**Cancelled By**
User Name
**Date/Time - Doesn't show**

@shanimal08

**Comment by mikethetike** [comment]
Changed the description to exclude one activity for all check ins to an event. Issue created to implement it: big-neon/bn-web#1656

**Comment by Anziskavds** [comment]
Tested successful on develop.

As per Shannon's above comment, there is no designs for Purchase: (Refunded amount if any) https://cl.ly/01d1bcfb8736 https://cl.ly/e968594047b7

**Not in designs, if still wanted can we get a design? Not sure where to put it**
@Tas4tari @shanimal08

**Comment by Anziskavds** [comment]
Tested develop on Mobile web. Tested unsuccessful in some of the fields:
 
Steps to reproduce:

- Purchase tickets: Instead of **[Purchasing User Name] purchased [# tickets] to [Event Name]** it shows the following **Purchased [# tickets] to [Event Name] (Order #).** The purchasing user name doesn't show on mobile web. https://cl.ly/3dbdcd8beadd
- Purchase tickets, expanded view: Event venue, name, city and state doesn't show. https://cl.ly/2695155590ea
- Purchase tickets: Code (Code, Type, Discount Amount if any) used in the order doesn't show. https://cl.ly/2b7fc22c36db
- Purchase tickets: CTA view order which links to Order Management View, links to the previous order management page. https://cl.ly/6943c15625fb
- Refund Created: Instead of **[Refunder Name] refunded [refund amount] to [User Name] (Order #)** it shows **[Refunder Name] refunded [refund amount](Order #)** https://cl.ly/818c46cfbaa9
- Items Refunded: Item Name, Item ID and Item Value. Not sure why there is a "$" in front of the item ID? https://cl.ly/b5bf44fe5ad6
- Ticket Transfer (3 states) each state includes:
Tickets - Pass
Ticket ID (Order # Link To Order) -Ticket ID shows but the order # doesn't show or link to order management
Initiated By - Fail
Transferrer Name - Fail
Date/Time - Fail (Expanded view)
Transfer Address - Fail
Email/Phone number transfer was sent to - Fail
**Successful State:**
Accepted By - Fail
User Name - Fail
Date/Time - Fail
**Cancelled By:**
User Name - Fail
Date/Time - Fail
https://cl.ly/b90f7b37b351
@shanimal08 
@Tas4tari

**Comment by Anziskavds** [comment]
Tested on develop, tested successful on web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Beta on web and mobile web.

**Comment by Anziskavds** [comment]
Related to issues #1507 and #1509 who tested unsuccessful I can't close this issue yet.

**Comment by Anziskavds** [comment]
Prod tested successful on web and mobile web.
