### ISSUE TITLE
Box Office - Cannot sell from paid hold

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#186]
Overview:

User cannot sell paid (full-priced or discounted) holds from the Box Office. When trying to sell a paid hold, the user gets a blank white screen as soon as user attempts to add a ticket to the cart.

Screengrab: https://cl.ly/e9a535425040
Screengrab: https://cl.ly/cb3273ba2707
Screengrab: https://cl.ly/cb3273ba2707

**Comment by harrisonlemon** [comment]
@zmelamed client is following up, do we have an eta?

**Comment by Jasonvdb** [comment]
Found the issue, it's caused by an edge case when a hold is created that reserves all the tickets for a ticket type and that visibility for that ticket type is set to "Only when available".

The box office is looking for details about the ticket type that it never received as it is hidden which is causing the web app to crash.

I'm looking into a solution hopefully I can do a hot fix into bn-web this weekend for it but I might need api assistance.

@harrisonlemon there is a temp solution for now to stop the box office from crashing and that's to update the "GA - FAN CLUB" ticket type to "Always visible". 

![Screenshot 2019-06-14 at 14 53 17](https://user-images.githubusercontent.com/5300488/59522212-60cd8680-8ece-11e9-8144-58ded17f4818.png)

**Comment by Jasonvdb** [comment]
@zmelamed @Tas4tari update here ☝️

**Comment by harrisonlemon** [comment]
Thanks @Jasonvdb!  The ticket type is not avail for sale online, and client is able to process necessary sales via box office. We can wait on the fix until next week's release (rather than a hotfix over the weekend)

**Comment by Jasonvdb** [comment]
Thanks, PR incoming that fixes this

**Comment by Anziskavds** [comment]
Tested on Beta and on Prod and is working as expected

**Comment by Anziskavds** [comment]
Tested on Prod and is working as expected. Box Office can sell tickets with a smart hold when it is created as a comp and when it is created as a discount hold. @Jasonvdb
