### ISSUE TITLE
Fees - Event Level Fees

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bigneon#187]
Context: More robust fee capabilities are now a need with All Aboard / Espee and Midway. Minimum org & event-level fee requirements:

1. We require the ability to add an additional fee per ticket type.
2. The amount allowed within the additional fee should be capped at $2.

**Comment by zmelamed** [comment]
@mikethetike I do like that and we'll save it. Because we aren't allowing them to reduce the rev share this isn't actually an override, it's strictly and addition.

The use case we're going to be satisfying is the event promoter, or venue owner who says "We want to get an extra $1 out of every ticket sold for this ticket type". Their current rev share isn't important to them in that decision.

While I agree there is value in showing the calculated fees for each ticket type, which we will eventually need to do as we build out more ticket fee/pricing options, it's not necessary to satisfy this use case so in an effort to minimize hours we spend on this feature which will be used infrequently (we suspect) we can postpone implementing that.

For this first iteration we only need the ability to add an additional per ticket type fee and we need to cap it at no more than $2. Mocks will be ready by Monday but this will follow the same Additional Options design pattern of other fields.

@Tas4tari please update the description of these issues to only include the ability to add an additional fee of up to $2 as we're not taking on the other items listed within this scope. That will come in the future.

**Comment by Tas4tari** [comment]
@zmelamed Please provide the design as well.

**Comment by mikethetike** [comment]
@zmelamed Just confirming: this fee is not split in anyway between the Org and Bigneon?

**Comment by zmelamed** [comment]
@mikethetike that's correct

**Comment by zmelamed** [comment]
![BigNeon_Studio__Master___1de73c2__sketch.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/a8c09ddc-9686-4b7b-aa01-7198d7a283af)

**Comment by Anziskavds** [comment]
Tested Prod on Web and Mobile web and it appears as expected
