### ISSUE TITLE
Ticket Settings - Ticket type is displayed multiple times purchase page

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#199]
REL: #198 

Overview: When creating a new event with multiple ticket types that sells by price tier rolling, user will occasionally encounter an error that deletes all but 1 of the ticket types. The user will then see a single ticket type displayed on the purchase page repeatedly. The inventory allotment in reporting will reflect this ticket type * how many times the ticket type displayed. 

Happens intermittently, difficult to reproduce - screenshots below.  

Screengrab: https://cl.ly/0285d7e3b849
Screengrab: https://cl.ly/ad4ab2639f14

**Comment by Jasonvdb** [comment]
Struggling to reproduce this one, still looking into it

**Comment by mikethetike** [comment]
This can be reproduced by:
1.  Create new event, don't save
2. Add a ticket type General Admission 1 -> Sales start immediately
3. Add a ticket type General Admission 2, first change the sales start to a specific date, then change it to Sales start after General admission 1. 
4. Click Save draft. You should receive a message "Could not insert record".
5. Repeatedly clicking Save draft will continue to create multiple General Admission 1, and error on GA2

The problem is that the API is not expecting a JSON packet for `POST ticket_types` with both start_date and parent_id set

Two things we need to do to solve this:
1.  After a ticket type has been saved, the web should add the id to it so that it is updated next time.
2. The error returned by the API is a 500 error. This should be a 422 validation error or 400 bad request saying what the problem with the JSON packet is.

**Comment by Anziskavds** [comment]
Tested on Develop, Beta and Prod and it looks like it is working as expected. I haven't received multiple ticket types when I tested according to @mikethetike comment above.
