### ISSUE TITLE
Ticket Settings - Ticket on sale date and time should default to 'Now' if they aren't explicitly set by the user

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#68]
Current behavior:
If I create a new ticket type and don't goto "Additional Options" to set the onsale date and time, and then immediately publish the event, it seems to default to 12:30pm the day it was created. This results in the ticket not going on sale if published earlier than 12:30pm and it's not clear why. 

Acceptance Criteria:
- [ ] When a user creates a new ticket type and doesn't set the on-sale date and time, it should be available for sale immediately if the event is published.

Overall
- [ ] Product/Design QA and approval
- [ ] Functional QA and approval

**Comment by Timo614** [comment]
https://github.com/big-neon/bn-web/blob/master/src/stores/eventUpdate.js#L126 

Took me a little bit to sort out but it looks like we're purposefully setting the default to 12:30 here.

I'll make the adjustment so that we just use the current time. We're okay with things like "1:21 PM" right? Or do we want it rounded down to the nearest hour? Not sure if that's displayed anywhere.

The backend requires a `start_date` for any ticket types that aren't the children of other ticket types (https://github.com/big-neon/bn-api/blob/master/db/src/models/ticket_types.rs#L688) so we end up requiring the field for any of these created by this flow.

How do we want the behavior to be with the unpublished? Just set the current time there as well? That was the previous behavior as we have the validation there requiring a start date set.

**Comment by mikethetike** [comment]
I think we should pass a `null` to the API to signify "Start immediately"

**Comment by Timo614** [comment]
> I think we should pass a null to the API to signify "Start immediately"

Having it send in a date if it's required feels a bit more explicit from an API perspective. Otherwise it feels a bit magical / I'd expect as an end user it would have no `start_date` associated if I passed `null` there.

**Comment by nine-tari** [comment]
Moved to QA as this was merged awhile back before we moved over to the new system.

**Comment by Anziskavds** [comment]
Reviewed:

- New ticket type created 
- Haven't selected anything at "Sales Start" or "Sales End"
- I could purchase tickets directly after I created the new ticket type
- I went back to the admin user to see what is showed under "Sales Start" and "Sales end" and "Sales Start" was on "Immediately" and "Sales End" on "Event End".


https://cl.ly/01f1ff016ea4
