### ISSUE TITLE
Holds - UX Bugs

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#80]
Scenario (screenshot attached):
- I added my name to an existing hold that is a "Discount" hold
  - Expected behavior: My name should appear on that holds list of names with the same settings as the hold and not on the list of  primary holds
  - Actual behavior: My name appeared on that holds list of names, but also appeared on the primary list of holds and is listed as a comp...
- I tried to redeem the hold, and received no feedback after submitting my code. It turned out the ticket type was off-sale, but I should have received feedback
- I changed the sale date on the ticket type so that the ticket type would be listed on sale. I entered my hold code and, though it said the code had been applied, the price was still $10 even though my hold code was listed as a comp

Overall
- [ ] Product/Design QA and approval
- [ ] Functional QA and approval
![Buy_tickets_-_Spoon_and_Big_Neon___Concert_and_Live_Event_Ticketing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46ca81831c968aaa84ecab509b10cfa73949287d1605ad2f4fa7ea2f806c7e0e013021c332070117a9bbcd44f7e8681ff6054db8be18192198797ec8e1d144ea45e37edc5d99a4fcc8139abd6e61f5819d4a6c16051f88f85837a2914fcf50f64be34853ad11646be0642a6e05c5402173363e6cfebecd5c958467aebb152a52c8ebe4fd1215a778dcd544.png)

**Comment by mikethetike** [comment]
@zmelamed The interface has changed, what should show with this new interface?
![image](https://user-images.githubusercontent.com/4200336/55944466-f2a7e180-5c48-11e9-8671-d17b754dec8f.png)

**Comment by Jasonvdb** [comment]
I looked into this today, I think there are 2 separate issues here.

For the inactive ticket pricing I've got a fix to popup with a warning when the code is valid but all the tickets it's valid for are currently not on sale. Let me know if you want to change the wording.
![Screenshot 2019-04-11 at 15 15 29](https://user-images.githubusercontent.com/5300488/55960270-b1c1c400-5c6c-11e9-90a0-fa1a0ec0826a.png)

The other issues are something I think we noticed a while ago and I think it's related to a bn-api PR (https://github.com/big-neon/bn-api/pull/1085) @Timo614 worked on a month back but we never got around to testing it because so many other things popped up that were priorities.

**Comment by zmelamed** [comment]
@Jasonvdb Can you you make it `Code is valid but no eligible tickets are available.`

Does that cover the `needs-layout-designs` label?

**Comment by Jasonvdb** [comment]
Sure no problem, will update the wording. 
I'll also work on getting bn-web working with Tim's PR today.
