### ISSUE TITLE
Consumer Web: Default # of tickets fluctuating between "0" and "2".

### ISSUE THREAD

**Issue by WolfManDan** [big-neon/bigneon#81]

**Comment by WolfManDan** [comment]
Check out this event:    To replicate, refresh screen 3-6 times and you will see the number of default tickets fluctuate between zero and 2.     https://www.bigneon.com/events/e720b4fc-7606-46b0-b818-6ec392ff53f1/tickets

**Comment by WolfManDan** [comment]
might be caching related, but another user (Chrome, web) had same experience. Thanks

**Comment by zmelamed** [comment]
Reproduced. Seems that if you go from the event page https://www.bigneon.com/events/e720b4fc-7606-46b0-b818-6ec392ff53f1 and click purchase tickets (which is the normal path for a user to take) it works (qty is set to 2). If you're on the ticket selection page and refresh it goes to 0.

**Comment by danielhalupka** [comment]
Main issue here is that sometimes the function setTicketSelectionFromExistingCart get's called before the selectedTicket is assigned into mobx because those two actions are async, so I'll add the ticket_types checker to wait for selectedTicket to be populated into the store. This is cause by mobx being out of sync with the app, might consider using redux :)
